name: Sync docs with S3

on:
  push:
    branches:
      - main #  change to `docs` later

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: 🛡️ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: 📦 Install dependencies
      run: npm ci

    - name: ⚡ Generate docs metadata
      run: npm run generate:metadata

    - name: 🪣 Sync to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'
        SOURCE_DIR: 'posts'
        DEST_DIR: 'posts'